# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/wmbm"

[social.params]
icon = "github"

# [[social]]
# identifier = "linkedin"
# name = "LinkedIn"
# url = "https://linkedin.com/in/william-baker-morrison"

# [social.params]
# icon = "linkedin"

# [[social]]
# identifier = "kaggle"
# name = "Kaggle"
# url = "https://kaggle.com/wilomentena"

# [social.params]
# icon = "kaggle"

# [[social]]
# identifier = "stackoverflow"
# name = "StackOverFlow"
# url = "https://stackoverflow.com/users/4320131/william-baker-morrison"

# [social.params]
# icon = "stackoverflow"


